---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 孙伟成.
--- DateTime: 2026/2/14 22:16
---
if(redis.call('GET',KEYS[1]) == ARGV[1]) then
    return redis.call('DEL',KEYS[1])
end
return 0